# Generated by Django 5.2.6 on 2025-09-23 22:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicero_experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitantes',
            name='data',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visitantes',
            name='fingerprint',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='visitantes',
            unique_together={('fingerprint', 'data')},
        ),
    ]
