# Generated by Django 5.2.6 on 2025-10-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicero_experience', '0002_visitantes_data_visitantes_fingerprint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitantes',
            name='transporte',
        ),
        migrations.AddField(
            model_name='visitantes',
            name='cor_raca',
            field=models.CharField(blank=True, choices=[('preto', 'Preto'), ('pardo', 'Pardo'), ('indigena', 'Indígena'), ('branco', 'Branco'), ('amarelo', 'Amarelo'), ('nao_informado', 'Não Informar')], default='nao_informado', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visitantes',
            name='genero',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outros', 'Outros'), ('nao_informado', 'Não Informar')], default='nao_informado', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visitantes',
            name='grupo',
            field=models.CharField(blank=True, choices=[('sim', 'Sim'), ('nao', 'Não'), ('desconhecido', 'Desconhecido')], default='desconhecido', max_length=20, null=True),
        ),
    ]
