# Generated by Django 5.2.6 on 2025-10-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicero_experience', '0003_remove_visitantes_transporte_visitantes_cor_raca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitantes',
            name='idade',
        ),
        migrations.AddField(
            model_name='visitantes',
            name='faixa_etaria',
            field=models.CharField(blank=True, choices=[('crianca', 'Criança (até 12 anos)'), ('adolescente', 'Adolescente (13 a 17 anos)'), ('jovem_adulto', 'Jovem Adulto (18 a 29 anos)'), ('adulto', 'Adulto (30 a 59 anos)'), ('idoso', 'Idoso (60+ anos)'), ('nao_informado', 'Não Informado')], default='nao_informado', max_length=20, null=True),
        ),
    ]
